In [44]:
import numpy as np
a = [1,2,3,4,5]
# inorder to run the code, we need to import numpy library first.
# After that, we need to list an array.

In [6]:
type(a)
# if we mention the type of array a , it is giving the list

list

In [10]:
b = np.array(a)
# If the array(a) assign it to b, we need to use np

In [11]:
b
# if we ask the "b", it will show us the array as list

array([1, 2, 3, 4, 5])

In [12]:
type(b)
# if we ask the type of "b", then it will show numpy.ndarray (that means n dimensional array)

numpy.ndarray

In [17]:
from array import array # (if we need to do it in google colab; from array function is not required)
arr1 = np.array(range(100)) # in python, we need to import the array menthod from the module.

In [18]:
arr1.ndim # range(100) means it will pick 0 to 100 nos in a straight line. So, it is a 1-dimensional array.

1

In [20]:
l = range(1000)

In [23]:
%timeit [i**2 for i in l]

330 µs ± 7.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [25]:
l = np.array(range(1000))

In [27]:
%timeit l**2

1.53 µs ± 14 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# From the above, we can understand, whether numpy will be useful or not. Time is reduced and the loops cycles will be increased.

In [28]:
arr1.shape

(100,)

In [29]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr2.ndim # ndim represents the no. of dimensions in an array

2

In [32]:
arr2.shape # exact shape in all dimensions

(3, 3)

In [34]:
np.arange() #arange syntax is arange(start,end,stop)

TypeError: arange() missing required argument 'start' (pos 1)

In [35]:
arr3 = np.arange(1,5)

In [36]:
arr3 # the last number will be excluded

array([1, 2, 3, 4])

In [37]:
arr3_step = np.arange(1,5,2) # here in the above series, step count will be included; [1, stepof 2; 3]
arr3_step

array([1, 3])

In [38]:
arr4 = np.arange(1,5,0.5) # For folating point numbers, every where the output will be displayinh in float with step count
arr4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [39]:
arr5 = np.array([1,2,3,4]) # normal array function with integers
arr5

array([1, 2, 3, 4])

In [40]:
arr6 = np.array([1,2,3,4.0]) # float is given in one numbers; other numbers are in integers
arr6 #But the output displayed everything in float. This is called TYPE CONVERSION IN NUMPY ARRAYS.

array([1., 2., 3., 4.])

In [41]:
arr7 = np.array(["Harry","is", "dog", 1, 2, 3]) # it converts everything into strings
arr7

array(['Harry', 'is', 'dog', '1', '2', '3'], dtype='<U5')

In [42]:
arr8 = np.array([1,2,3,4,5], dtype = "float") # we can alternatively use the dtype and convert it into float. 
arr8

array([1., 2., 3., 4., 5.])

In [45]:
m1 = np.arange(12)

In [46]:
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [47]:
m1[0]

0

In [48]:
m1[-1]

11

In [49]:
m1[1:3]

array([1, 2])

In [50]:
m1[1:3:2]

array([1])

In [51]:
m1[:2:2]

array([0])

In [52]:
m1[::]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
m1[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [54]:
m1[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [55]:
m1[:-1:-1]

array([], dtype=int32)

In [56]:
m1[::-2]

array([11,  9,  7,  5,  3,  1])

In [57]:
# we can also use list in numpy
m2 = np.array([100,200,300,400,500,600])
m2[[2,3,1,4,1,2,2]]

array([300, 400, 200, 500, 200, 300, 300])

In [58]:
m2[2,3]

IndexError: too many indices for array

In [60]:
!pip install --upgrade gdown
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Requirement already up-to-date: gdown in c:\users\jyks\anaconda3\lib\site-packages (4.7.3)


Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: C:\Users\jyks\Bala\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<00:00, 2.97MB/s]


In [61]:
score = np.loadtxt('survey.txt', dtype='int') #Calculating net promoter score
type(score)

numpy.ndarray

In [62]:
score[:5]

array([ 7, 10,  5,  9,  9])

In [64]:
total = len(score)
total

1167

In [65]:
detractors = score[score<=6]
detractors

array([5, 4, 4, 5, 1, 5, 5, 1, 4, 5, 4, 4, 4, 5, 1, 4, 1, 4, 1, 5, 5, 1,
       1, 4, 1, 5, 4, 1, 1, 4, 1, 5, 1, 4, 4, 1, 1, 1, 1, 1, 1, 1, 4, 1,
       1, 5, 5, 5, 4, 4, 1, 4, 1, 4, 1, 5, 1, 1, 5, 4, 4, 4, 4, 1, 4, 5,
       4, 4, 1, 1, 5, 5, 1, 5, 1, 5, 5, 4, 5, 4, 1, 1, 1, 1, 4, 1, 4, 4,
       5, 4, 1, 1, 1, 1, 5, 4, 5, 5, 4, 1, 5, 1, 4, 4, 1, 1, 1, 4, 4, 5,
       5, 4, 5, 5, 5, 1, 4, 1, 5, 5, 1, 5, 1, 1, 5, 5, 4, 4, 1, 4, 4, 4,
       1, 1, 4, 4, 4, 5, 5, 1, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 5, 4, 4,
       5, 1, 4, 5, 5, 5, 1, 5, 4, 1, 1, 5, 5, 5, 4, 5, 4, 4, 1, 4, 4, 4,
       4, 5, 1, 5, 5, 1, 4, 4, 5, 1, 1, 4, 5, 5, 5, 1, 4, 5, 5, 4, 1, 5,
       5, 5, 1, 1, 5, 5, 1, 1, 1, 4, 5, 5, 4, 4, 4, 5, 1, 4, 1, 4, 5, 4,
       5, 5, 1, 5, 1, 5, 5, 1, 4, 5, 5, 4, 1, 5, 1, 4, 1, 4, 1, 1, 1, 1,
       1, 1, 4, 1, 5, 4, 5, 1, 5, 1, 5, 4, 4, 4, 4, 5, 5, 1, 4, 1, 5, 5,
       1, 4, 1, 1, 4, 4, 4, 4, 1, 4, 1, 1, 4, 1, 5, 4, 1, 1, 5, 4, 5, 4,
       4, 4, 1, 5, 5, 1, 4, 5, 4, 4, 4, 1, 4, 1, 4,

In [66]:
num_detractors = len(detractors)
num_detractors

332

In [71]:
passive = [s for s in score if s>=7 and s<=8]
passive
num_passive = len(passive)
num_passive

226

In [73]:
promoters = score[score>=9]
promoters
num_promoters = len(promoters)
num_promoters

609

In [74]:
percentage_detractors = (num_detractors/total)*100
percentage_detractors

28.449014567266495

In [75]:
percentage_promoters = (num_promoters/total)*100
percentage_promoters

52.185089974293064

In [77]:
nps = percentage_promoters - percentage_detractors
nps

23.73607540702657

In [78]:
nps = np.round(nps,2)
nps

23.74

In [81]:
np.arange(22,71,2) #Question 1

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [82]:
np.arange(21,72,2) # Question2

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [83]:
arr9 = np.array([10,20,30,40,50])
float(arr9)

TypeError: only size-1 arrays can be converted to Python scalars

In [84]:
arr9.to_float()

AttributeError: 'numpy.ndarray' object has no attribute 'to_float'

In [85]:
type(arr9,dtype='float64')

TypeError: type() takes 1 or 3 arguments

In [87]:
arr9.astype('float64') #Question 3 - Convert the array into floats.

array([10., 20., 30., 40., 50.])

In [88]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x>=-5

array([ True,  True,  True,  True,  True,  True,  True,  True, False])

In [90]:
x<=15

array([ True,  True, False, False,  True,  True, False,  True,  True])

In [91]:
(x>=-5) & (x<=15)

array([ True,  True, False, False,  True,  True, False,  True, False])

In [92]:
x[(x>=-5) & (x<=15)]

array([-5,  9, -3,  5, 10])

In [94]:
x[(x>=-5) & (x<=15)] *= -1

In [95]:
print(x)

[ -5  -9  20  25  -3   5  16 -10  -8]


In [96]:
arr10 = np.array([1, 2, 3, 4])
arr10[2]

3

In [97]:
arr10[-2]

3

In [100]:
arr11 = np.array([10, 12, 15, 17, 2, 5, 4, 6])
arr11

array([10, 12, 15, 17,  2,  5,  4,  6])

In [102]:
arr11(2,4,6,8)

TypeError: 'numpy.ndarray' object is not callable

In [103]:
arr11[[0,2,4,6]]

array([10, 15,  2,  4])

In [112]:
arr13 = np.array([1,2,3,4,5,6,7,8])
arr13[::2] = range(10,50,10)
print(arr13)

[10  2 20  4 30  6 40  8]
